import {
  predictor,
  cityscapeForecast,
  niftique,
  netzon5,
  grabNgo,
  budgetBuddy,
  laBelle,
  legacyCodeHQ,
  todoSentinel,
  markdown,
  figma,
  githubIcon,
  html5,
  css,
  reactIcon,
  tailwind,
  typescript,
  javascript,
  node,
  mongodb,
  next,
  python,
  firebase,
  postman,
  vscode,
  vercel,
  netlify,
  redux,
  express,
  flutter,
  dart,
  redis,
  aws,
  gcp,
  docker,
  shadcn,
} from '../assets';

export const navLinks: NavLink[] = [
  { id: 'about', title: 'About' },
  { id: 'project', title: 'Work' },
  { id: 'contact', title: 'Contact' },
];

export const skillSet: SkillItem[] = [
  // Frontend
  { name: 'React JS',     icon: reactIcon },
  { name: 'Next JS',      icon: next },
  { name: 'TypeScript',   icon: typescript },
  { name: 'JavaScript',   icon: javascript },
  { name: 'Tailwind CSS', icon: tailwind },
  { name: 'Redux',        icon: redux },
  { name: 'Flutter',      icon: flutter },
  { name: 'Dart',         icon: dart },
  { name: 'Shadcn',       icon: shadcn },
  { name: 'HTML 5',       icon: html5 },
  { name: 'CSS 3',        icon: css },
  // Backend
  { name: 'Node JS',      icon: node },
  { name: 'Express.js',   icon: express },
  { name: 'Python',       icon: python },
  { name: 'Firebase',     icon: firebase },
  // Databases & Cloud
  { name: 'MongoDB',      icon: mongodb },
  { name: 'Redis',        icon: redis },
  { name: 'AWS',          icon: aws },
  { name: 'GCP',          icon: gcp },
  { name: 'Docker',       icon: docker },
  // Tools
  { name: 'GitHub',       icon: githubIcon },
  { name: 'Figma',        icon: figma },
  { name: 'VSCode',       icon: vscode },
  { name: 'Postman',      icon: postman },
  { name: 'Vercel',       icon: vercel },
  { name: 'Netlify',      icon: netlify },
  { name: 'Markdown',     icon: markdown },
];

export const timeline: TimelineEntry[] = [
  {
    id: 0,
    title: 'Repository Accidentally Initialized',
    location: 'Unknown',
    date: 'Sometime, Somewhere',
    type: 'origin',
    description: [
      'git init ran without consent. No README. No .gitignore.',
      'Author had no idea what they were getting into.',
      'First commit pushed directly to main. No review. No regrets.',
    ],
  },
  {
    id: 1,
    title: 'B.Tech — Electrical & Electronics Engineering',
    location: 'Vellore Institute of Technology, Chennai',
    date: 'Jul 2019 – May 2023',
    type: 'education',
    description: ['CGPA: 7.88'],
  },
  {
    id: 2,
    title: 'Web Developer Intern — SkillVertex',
    location: 'Remote',
    date: 'Jul 2022 – Oct 2022',
    type: 'internship',
    description: [
      'Shipped responsive UI components using HTML, CSS, and JavaScript as part of an agile team, gaining hands-on exposure to real-world development workflows.',
      'Participated in sprint planning and daily standups, contributing to on-time feature delivery while applying clean-code practices across assigned modules.',
    ],
  },
  {
    id: 3,
    title: 'Frontend Developer — Legacy Code HQ',
    location: 'Remote',
    date: 'Aug 2023 – Jan 2024',
    type: 'fulltime',
    description: [
      'Built an interactive dependency-graph visualizer and class-hierarchy mapper for legacy Kotlin codebases, processing 50K+ lines of code and cutting migration cycle time by 50%.',
      'Optimised the platform to a 92 Lighthouse performance score, directly improving search ranking by 20%.',
    ],
  },
  {
    id: 4,
    title: 'Frontend Developer — Adrig Technologies',
    location: 'Remote',
    date: 'Jan 2024 – Jun 2024',
    type: 'fulltime',
    description: [
      'Architected the company web presence end-to-end — product demos, technical documentation, and a blog platform — using Next.js and responsive design principles.',
      'Designed proof-of-concept dashboards for Southern Railways Rolling Block Management System with role-based access control tailored to supervisors, station masters, and back-office staff.',
    ],
  },
  {
    id: 5,
    title: 'Frontend Developer — KANISKART (Freelance)',
    location: 'Remote',
    date: 'Mar 2024 – Aug 2024',
    type: 'freelance',
    description: [
      'Engineered a full-featured e-commerce platform from scratch with Next.js, Tailwind CSS, TypeScript, and Shadcn — covering storefront, cart, login/register, and product pages.',
      'Built the admin suite for product management, order processing, and user management, reducing manual ops overhead significantly.',
      'Collaborated directly with the client through the full cycle — requirements, design iterations, code reviews, and delivery — following agile practices throughout.',
    ],
  },
  {
    id: 6,
    title: 'Junior Frontend Developer — TerraByte Technologies',
    location: 'Bangalore',
    date: 'Jul 2024 – May 2025',
    type: 'fulltime',
    description: [
      'Built a centralised analytics system to track user lifecycle events, eliminating scattered instrumentation and reducing codebase by 1,500+ lines.',
      'Engineered a recommendation engine on user behavioural data, improving retention to D1: 43% and D7: 24%.',
      'Developed internal debugging and QA tooling for recommendation logic, matchmaking, FTUE flows, and analytics — measurably improving testing efficiency across the team.',
      'Implemented a priority-based popup manager that eliminated UI conflicts and improved interaction flow across the app.',
    ],
  },
  {
    id: 7,
    title: 'SDE-1 — TerraByte Technologies',
    location: 'Bangalore',
    date: 'May 2025 – Present',
    type: 'fulltime',
    description: [
      'Reduced content production time by 75% (2 days → 0.5 day) by building an automated, end-to-end multi-modal content generation pipeline using LLMs and structured prompts.',
      'Scaled the application from 5 to 2,000+ DAU (150K MAU) by rearchitecting with caching and async processing, achieving sub-150ms average latency.',
      'Engineered an asset delivery system with intelligent caching, parallel downloads, and on-demand loading — cutting launch time from 15–20s to 4–5s.',
      'Architected real-time matchmaking and backend coordination systems, increasing multiplayer engagement by 2×.',
      'Built a Unity ↔ React/Flutter event-driven bridge with retry and fallback mechanisms, reducing data sync errors by 60%.',
    ],
  },
];

export const projects: Project[] = [
  {
    title: 'Legacy Code HQ',
    description:
      'Built frontend interface for a code migration platform with interactive dependency graph visualization and class hierarchy mapping for legacy Kotlin codebases, processing 50K+ lines of code. Achieved a 92 Lighthouse performance score.',
    tags: [
      { skills: 'next js', color: 'pink-text-gradient' },
      { skills: 'tailwind css', color: 'green-text-gradient' },
      { skills: 'typescript', color: 'blue-text-gradient' },
      { skills: 'markdown', color: 'pink-text-gradient' },
    ],
    image: legacyCodeHQ,
    status: 'completed',
    demo: 'https://www.legacycode.com/',
  },
  {
    title: 'ToDo Sentinel',
    description:
      'Task management app built with TypeScript, Next.js, Tailwind CSS, and Firestore. Supports customizable tasks, deadlines, and seamless CRUD operations with a dynamic, real-time experience.',
    tags: [
      { skills: 'next js', color: 'pink-text-gradient' },
      { skills: 'typescript', color: 'blue-text-gradient' },
      { skills: 'firebase', color: 'pink-text-gradient' },
      { skills: 'tailwind css', color: 'green-text-gradient' },
    ],
    image: todoSentinel,
    source: 'https://github.com/JamesUdy/To-Do-Sentinel.git',
    status: 'completed',
    demo: 'https://to-do-sentinel.vercel.app/',
  },
  {
    title: 'Cityscape Forecast',
    description:
      'Global weather app with multi-day forecasts and air quality data via weather API integration. Built with Next.js, TypeScript, and Tailwind CSS for informed urban planning insights.',
    tags: [
      { skills: 'next js', color: 'pink-text-gradient' },
      { skills: 'tailwind css', color: 'green-text-gradient' },
      { skills: 'typescript', color: 'blue-text-gradient' },
      { skills: 'weather api', color: 'pink-text-gradient' },
    ],
    image: cityscapeForecast,
    source: 'https://github.com/JamesUdy/Cityscape_Forecast',
    status: 'completed',
    demo: 'https://cityscape-forecast.vercel.app/',
  },
  {
    title: 'Niftique — NFT Marketplace',
    description:
      'NFT marketplace with real-time crypto converter via APIs and OpenSea integration. Supports NFT creation, editing, buying, and selling with a secure, responsive interface.',
    tags: [
      { skills: 'react', color: 'pink-text-gradient' },
      { skills: 'tailwind css', color: 'green-text-gradient' },
      { skills: 'javascript', color: 'blue-text-gradient' },
      { skills: 'opensea api', color: 'pink-text-gradient' },
    ],
    image: niftique,
    source: 'https://github.com/JamesUdy/Niftique',
    status: 'developing',
    demo: 'https://niftique.vercel.app/home',
  },
  {
    title: 'Grab N Go',
    description:
      'Responsive grocery list app with Firebase real-time storage and Firebase Authentication for data privacy. Full CRUD operations with a clean, intuitive interface.',
    tags: [
      { skills: 'javascript', color: 'blue-text-gradient' },
      { skills: 'css', color: 'green-text-gradient' },
      { skills: 'html', color: 'pink-text-gradient' },
      { skills: 'firebase', color: 'blue-text-gradient' },
    ],
    image: grabNgo,
    source: 'https://github.com/JamesUdy/Grab_N_Go',
    status: 'completed',
    demo: 'https://grab-n-go.netlify.app/',
  },
  {
    title: 'Budget Buddy',
    description:
      'Personal finance tracker with voice recognition for automated income and expense entry. Features real-time visual graphs for data-driven financial decisions.',
    tags: [
      { skills: 'react', color: 'blue-text-gradient' },
      { skills: 'javascript', color: 'pink-text-gradient' },
      { skills: 'tailwind css', color: 'green-text-gradient' },
      { skills: 'voice assist', color: 'blue-text-gradient' },
    ],
    image: budgetBuddy,
    source: 'https://github.com/JamesUdy/Budget-Buddy',
    status: 'completed',
    demo: 'https://budget-buddy15.vercel.app/',
  },
  {
    title: 'Netzon5 — OTT Streaming Platform',
    description:
      'Responsive OTT platform using the TMDB API to search 1000+ films with narrative details, IMDB ratings, genre, and release year. Supports multitasking across multiple pages.',
    tags: [
      { skills: 'javascript', color: 'blue-text-gradient' },
      { skills: 'html', color: 'green-text-gradient' },
      { skills: 'tailwind css', color: 'pink-text-gradient' },
      { skills: 'tmdb api', color: 'blue-text-gradient' },
    ],
    image: netzon5,
    source: 'https://github.com/JamesUdy/Netzon5',
    status: 'developing',
  },
  {
    title: 'Real-Estate Price Predictor',
    description:
      'Machine learning model blending Data Science and Web Development to estimate house prices in Bangalore. Trained on 10,000+ rows for highly accurate predictions using linear regression.',
    tags: [
      { skills: 'python', color: 'pink-text-gradient' },
      { skills: 'machine learning', color: 'green-text-gradient' },
      { skills: 'javascript', color: 'blue-text-gradient' },
      { skills: 'html/css', color: 'pink-text-gradient' },
    ],
    image: predictor,
    source: 'https://github.com/JamesUdy/RE_Price_Prediction',
    status: 'completed',
  },
  {
    title: 'La Belle Assiette',
    description:
      'Food ordering and restaurant table reservation platform with multi-page navigation and a user-friendly menu browsing experience.',
    tags: [
      { skills: 'html', color: 'green-text-gradient' },
      { skills: 'css', color: 'blue-text-gradient' },
      { skills: 'javascript', color: 'pink-text-gradient' },
    ],
    image: laBelle,
    source: 'https://github.com/JamesUdy/La-Belle-Assiette',
    status: 'completed',
    demo: 'https://la-belle-assiette.netlify.app/',
  },
];
